# -*- coding: utf-8 -*-
"""Ejercicios

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WMNl6p5tbvDCitZ62QS7hn6IBki4Q_2Z
"""

# tipos de datos

a = 10
b = 1.5
c = "Hola"
d = True
e = None
print(a)
print(b)
print(c)
print(d)
print(e)
print(type(a))
print(type(b))
print(type(c))
print(type(d))
print(type(e))

# condicionales

numero_1 = 3
numero_2 = 2

if numero_1 == numero_2:
    print(str(numero_1) + "es igual a " + str(numero_2))
elif numero_1 < numero_2:
    print(str(numero_1) + "es menor a" + str(numero_2))
elif numero_1 > numero_2:
    print(str(numero_1) + "es mayor a" + str(numero_2))

# bucle while

a = 10
while a > 0:
    print(a)
    a -= 1

# bucle for

a = [1,2,3,4,5,6,7,8,9,10]

for i in a:
    print(i)

# diccionario

a = {
    "nombre": "Juan",
    "apellido": "Perez",
    "edad": 20
}

print("-------")
print(a["nombre"])
print(a["apellido"])
print(a["edad"])
print("-------")

for x in a:
    print(x + " : " + str(a[x]))